/* generated by pull.js */
const manifest = {
    name: 'Send to SE!',
    description: "Send the current project to a console running Scratch Everywhere (SE!) over the local network directly from the editor.",
    tags: [
        'recommended'
    ],
    userscripts: [
        {
            url: 'userscript.js'
        }
    ],
    userstyles: [
        {
            url: 'style.css'
        }
    ],
    enabledByDefault: true // ??
};
export default manifest;
